import json
import os

import dspy
from dotenv import load_dotenv
from dspy.teleprompt import BootstrapFewShot

# Import our uncompiled modules
from dspy_modules import (
    ApproximationJudge,
    ComputationJudge,
    LogicalGapJudge,
    ToyCaseJudge,
)

# Load environment variables
load_dotenv()
nim_key = os.getenv("NVIDIA_API_KEY")

if not nim_key:
    raise ValueError("NVIDIA_API_KEY not found. Please check your .env file.")

nim_lm = dspy.LM(
    model='openai/meta/llama-3.1-70b-instruct',
    api_key=nim_key,
    api_base='https://integrate.api.nvidia.com/v1'
)

dspy.settings.configure(lm=nim_lm)

# DATA PREPARATION

def load_and_format_dataset(filepath="artifacts\\data_curated\\raw_proofs.json"):
    """Loads the raw JSON and converts it into DSPy Examples."""
    with open(filepath, "r", encoding="utf-8") as f:
        raw_data = json.load(f)
    dataset = []
    for data in raw_data:
        # Determine the expected boolean answers based on the flaw_type
        flaw = data["flaw_type"]
        # Create a dspy.Example. 
        # We include the inputs (problem, proof) and the expected outputs.
        example = dspy.Example(
            problem=data["prompt_used"],
            proof=data["generated_proof"],
            uses_toy_case=(flaw == "toy_case"),
            has_logical_gap=(flaw == "logical_gap"),
            uses_illegal_approximation=(flaw == "approximation"),
            has_computation_error=(flaw == "computation_error")
        ).with_inputs("problem", "proof")
        dataset.append(example)
    return dataset

# DSPy needs a metric function to know if a bootstrapped example is "Good" or "Bad".
# We define simple exact-match metrics for our booleans.

def toy_case_metric(example, pred, trace=None):
    return example.uses_toy_case == pred.uses_toy_case

def logical_gap_metric(example, pred, trace=None):
    return example.has_logical_gap == pred.has_logical_gap

def approximation_metric(example, pred, trace=None):
    return example.uses_illegal_approximation == pred.uses_illegal_approximation

def computation_metric(example, pred, trace=None):
    return example.has_computation_error == pred.has_computation_error

# COMPILATION / OPTIMIZATION
def optimize_judges():
    print("Loading dataset...")
    trainset = load_and_format_dataset()
    # Initialize the DSPy Optimizer
    # max_bootstrapped_demos: How many successful reasoning chains to inject into the prompt
    # max_labeled_demos: How many static examples to include
    teleprompter = BootstrapFewShot(
        metric=None, # We will override this per judge
        max_bootstrapped_demos=3,
        max_labeled_demos=1
    )
    os.makedirs(os.path.join("artifacts", "compiled_judges"), exist_ok=True)
    # 1. Optimize Toy Case Judge
    print("\n Compiling Toy Case Judge ")
    teleprompter.metric = toy_case_metric
    compiled_toy_judge = teleprompter.compile(ToyCaseJudge(), trainset=trainset)
    compiled_toy_judge.save(os.path.join("artifacts", "compiled_judges", "toy_case_judge.json"))
    
    # 2. Optimize Logical Gap Judge
    print("\n Compiling Logical Gap Judge ")
    teleprompter.metric = logical_gap_metric
    compiled_gap_judge = teleprompter.compile(LogicalGapJudge(), trainset=trainset)
    compiled_gap_judge.save(os.path.join("artifacts", "compiled_judges", "logical_gap_judge.json"))
    
    # 3. Optimize Approximation Judge
    print("\n Compiling Approximation Judge ")
    teleprompter.metric = approximation_metric
    compiled_approx_judge = teleprompter.compile(ApproximationJudge(), trainset=trainset)
    compiled_approx_judge.save(os.path.join("artifacts", "compiled_judges", "approximation_judge.json"))
    
    # 4. Optimize Computation Judge
    print("\n Compiling Computation Judge ")
    teleprompter.metric = computation_metric
    compiled_comp_judge = teleprompter.compile(ComputationJudge(), trainset=trainset)
    compiled_comp_judge.save(os.path.join("artifacts", "compiled_judges", "computation_judge.json"))
    
    print("\nAll judges successfully optimized and saved to 'artifacts/compiled_judges/'!")
    
    # Inspect one of the generated prompts
    print("\nExample Optimized Prompt for Toy Case Judge:")
    print(nim_lm.history[-1])

    print("\nSaving compiled prompt evidence...")
    evidence_path = os.path.join("artifacts/evaluation_results", "compiled_prompts.txt")
    
    with open(evidence_path, "w", encoding="utf-8") as f:
        f.write("DSPy OPTIMIZED PROMPT EVIDENCE\n")
        f.write("This file contains the raw, compiled prompts generated by BootstrapFewShot.\n")
        f.write("Notice the injected <Reasoning> steps and Few-Shot examples.\n\n")
        # We grab the last 4 interactions from the LM's history
        for i, interaction in enumerate(nim_lm.history[-4:]):
            f.write(f" COMPILED PROMPT TRACE {i+1} \n\n")
            # Extract the raw prompt text sent to the API
            if isinstance(interaction, dict):
                prompt_text = interaction.get('prompt') or interaction.get('messages') or str(interaction)
                f.write(str(prompt_text))
            else:
                f.write(str(interaction))
            f.write("\n\n" + "="*80 + "\n\n")
    print(f"Evidence saved to '{evidence_path}'! Include this in your submission.")

if __name__ == "__main__":
    optimize_judges()
